### ISSUE TITLE
NumberGroup: make sure passed can be grouped correctly

### ISSUE THREAD

**Issue by andres-lowrie** [andres-lowrie/human#2]
Notice here that the expected output is not a correct grouping:

https://github.com/andres-lowrie/human/blob/e8a379ce38131003e2f20512a1ef539e2b3b63f2/parsers/number_test.go#L49

this is because the implementation doesn't do anything to check the input and just starts throwing commas at it.

It could be useful to guard against this

**Comment by bobross419** [comment]
I did regex for this here: https://github.com/andres-lowrie/human/blob/master/parsers/numword.go#L71

**Comment by andres-lowrie** [comment]
sweet!
